config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords,], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "homes#top"
    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:edit, :show, :update, :index]
    resources :orders, only: [:update, :show]
    resources :order_details, only: [:update]
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "/orders/thanks" => "orders#thanks"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:edit, :update]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "/cart_items" => "cart_items#all_destroy"
    get 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders, only: [:new, :create, :index, :show]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :addresses, only: [:index, :edit ,:create, :update, :destroy]
  end
 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  private
def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  attachment :image
  belongs_to :genre 
  
  def with_tax_price
    (price * 1.1).floor
  end
  # 消費税を求めるメソッド
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, payment_confirmation: 1, production: 2, preparing_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { not_startable: 0, waiting_production: 1, production: 2, complete_production: 3 }

  
  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def create
    @genre = Genre.new(genre_params)
    
    if @genre.save
      flash[:notice] = 'You have created genre successfully.'
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end

  end

  def index
    #@genres = Genre.all
    @genres = Genre.page(params[:page]).reverse_order
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = 'You have updated genre successfully.'
       redirect_to admin_genres_path
    else
       render :edit
    end
    
  end

  # 投稿データのストロングパラメータ
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders= Order.page(params[:page]).reverse_order
    
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 
 def new
    @item=Item.new
    
 end
 
  def create
    @item = Item.new(item_params)
    # if
    @item.save
    redirect_to admin_item_path(@item)
    # else
    #   redirect_to request.referer,notice:"新規登録できませんでした"
    # end 
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = 'You have updated item successfully.'
       redirect_to admin_item_path
    else
       render :edit
    end
  end
  
  def index 
    @items=Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  
  private
    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order= Order.find(params[:id])
    @order_detail= @order.order_details
    #@customer = Customer.find(params[:id])
    #@orders = @customer.orders
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = 'You have updated order successfully.'
      redirect_to admin_root_path
    else
      render :show
    end
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<main>
   <div class='container'>
     <div class='row'>
       <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
         <h1>ジャンル編集</h1>
            <!--エラーメッセージここから-->
            <% if @genre.errors.any? %>
              <div id="error_explanation">
                <h3><%= @genre.errors.count %> error prohibited this obj from being saved:</h3>
                <ul>
                  <% @genre.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <!--エラーメッセージここまで-->
         <!-- 編集フォーム -->
         
              <%= form_with model:@genre, url: admin_genre_path , local:true do |f| %>
                 <div class="form-group">
                  <label for="genre_name">ジャンル</label>
                  <%= f.text_field :name, :class =>'form-control genre_name' %>
                  <%= f.submit '変更を保存', class:"btn btn-success" %>
                 </div>
              <% end %>
         
         <!-- 編集フォームここまで -->
         
         <%= link_to"ジャンル一覧へ戻る",admin_genres_path %>
       </div>
     </div>
   </div>
</main>

app/views/admin/genres/index.html.erb
<main>
   
   <div class='container px-5 px-sm-0'>
      
     <!--エラーメッセージここから-->
        <% if @genre.errors.any? %>
           <div id="error_explanation">
              <h2><%= @genre.errors.count %> errors prohibited this obj from being saved:</h2>
              <ul>
                 <% @genre.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                 <% end %>
              </ul>
           </div>
        <% end %>
     <!--エラーメッセージここまで-->
     
     <div class='row'>
       <div class='col-md-12 offset-md-1'>
         <h2>ジャンル一覧・追加</h2>
         <!-- 登録フォーム -->
         <table class='table table-hover table-inverse'>
              <%= form_with model: @genre, url: admin_genres_path , local:true do |f| %>
                <table class='table table-hover table-inverse'>
                 <div class="form-group">
                  <td>ジャンル</td>
                  <td><%= f.text_field :name, :class =>'form-control genre_name' %></td>
                  <td><%= f.submit '新規登録', class:"btn btn-success" %></td>
                 </div>
                </table>
              <% end %>
         </table>
         <!-- 登録フォームここまで -->
         <!-- ジャンル一覧表示 -->
         <table class='table table-hover table-inverse'>
           <thead>
             <tr>
               <th>ジャンル</th>
               <th colspan="3"></th>
             </tr>
           </thead>
           <tbody>
             <% @genres.each do |genre| %>
               <tr>
                 <td>
                     <%= genre.name %>
                 </td>
                 <td>
                     <%= link_to"編集する",edit_admin_genre_path(genre.id) ,class:"btn btn-sm btn-success"%>
                 </td>
               </tr>
             <% end %>
           </tbody>
         </table>
         <!-- ジャンル一覧表示ここまで -->
        <%= paginate @genres %>
       </div>
     </div>
   </div>
</main>

app/views/admin/items/edit.html.erb
<div class='container'>
     <div class='row'>
       <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
         <h1>商品編集</h1>
         
            <!--エラーメッセージここから-->
            <% if @item.errors.any? %>
              <div id="error_explanation">
                <h3><%= @item.errors.count %> error prohibited this obj from being saved:</h3>
                <ul>
                  <% @item.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <!--エラーメッセージここまで-->
            
         <!-- 編集フォーム -->
              
              <%= form_with model: @item, url: admin_item_path , local:true do |f| %>
                <table class='table table-hover table-inverse'>
                  <!-- 画像 -->
                  <tr>
                    <td>商品画像</td>
                    <td><%= f.attachment_field :image, placeholder: "商品画像",:class =>"form-control-file user_image" %></td>
                  </tr>
                  
                  <!-- 商品名 -->
                  <tr>
                    <td>商品名</td>
                    <td><%= f.text_field :name, autofocus: true, :class =>'form-control book_title'%></td>
                  </tr>
                  
                  <!-- 商品説明 -->
                  <tr>
                    <td>商品説明</td>
                    <td><%= f.text_area :introduction, autofocus: true, :class =>'form-control book_body'%></td>
                  </tr>
                  
                  <!-- ジャンル -->
                  <tr>
                    <td>ジャンル</td>
                    <td>
                      <%= f.collection_select :genre_id, Genre.all, :id, :name %>
                    </td>
                  </tr>
                  
                  <!-- 税抜価格 -->
                  <tr>
                    <td>税抜価格</td>
                    <td><%= f.text_field :price, autofocus: true, :class =>'form-control book_title'%></td>
                  </tr>
                  
                  <!-- 販売ステータス -->
                  <tr>
                    <td>販売ステータス</td>
                    <td>
                      <%=f.radio_button :is_active, TRUE %>販売中 <%=f.radio_button :is_active, FALSE %>販売停止中
                    </td>
                  </tr>
                </table>
                <!-- 決定ボタン -->
                  <div class="form-group">
                    <%= f.submit "変更を保存", :class=>"btn btn-success"%>
                  </div>
              <% end %>
               
         <!-- 編集フォームここまで -->
         
         <%= link_to"商品詳細へ戻る",admin_item_path %>
       </div>
     </div>
</div>

app/views/admin/items/index.html.erb
   <h2 class="table-secondary mb-3 ml-3 d-inline">商品一覧</h2>
 <table class="table table-hover table-bordered table-inverse">
        <div></div>
        <thead class="table-secondary">
  　　　  　<th>商品id</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
        
          <th>ステータス</th>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %> </td>
               <td><%= link_to item.name,admin_item_path(item) %></td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td> <% if item.is_active? %>
            <span class="text-success font-weight-bold">販売中</span>
          <% else %>
            <span class="text-danger font-weight-bold">販売停止中</span>
          <% end %></td>
          　　    </tr>
          <% end %>
        </tbody>
      </table>

app/views/admin/items/new.html.erb
<div class="row">
<div class="col-sm-8 px-sm-0 offset-sm-1">
<h1>商品新規投稿</h1>
<div class="col-sm-10 px-sm-0 mx-auto md-5">
<%= form_with url:admin_items_path, model:@item, local:true do |f| %>
<table>
  <tr>
  <th>商品画像</th>
  <th><%= f.attachment_field :image %></th></tr>
  <tr>
  <th>商品名</th>
  <th><%= f.text_field :name , :size=>"30"%></th></tr>
  <tr>
  <th>商品説明</th>
  <th><%= f.text_area :introduction , :size=>"33x5"%></th></tr>
  <tr>
  <th>ジャンル</th>
  <th><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --"  %></th></tr>
  <tr>
  <th>税抜価格</th>
  <th><%= f.text_field :price , :size=>"30" %></th></tr>
  <tr>
  <th>販売ステータス</th>
  <th><%= f.radio_button :is_active, true %> 販売中
  <%= f.radio_button :is_active, false %> 販売停止中</th></tr>
  <tr>
  <th>
  <%= f.submit '新規登録', class: " offset-sm-8 btn btn-outline-success" %>
  </th></tr>
<% end %>
</div></table ></div></div>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
 <div class="row">
  <div class="container">
  <div class="row">
 <div class="col-md-6">
 <%= attachment_image_tag @item, :image, fallback: "no_image.jpg", size: "300x200" %>
 </div> 
 <div class="col-md-6">
  <table > <tr>
   <th>商品名</th>
   <td><%= @item.name %></td> </tr>
  <tr>
   <th>商品説明</th>
   <td><%= @item.introduction %></td>  </tr>
  <tr>
   <th>ジャンル</th>
   <td><%= @item.genre.name %></td> </tr>
   <tr>
  <th>税込価格<br>(税抜価格)</th>
  <td><%= @item.with_tax_price %>円<br>(<%= @item.price %>円）</td> </tr>
  <tr>
  <th>販売ステータス</th>
  <td>
 <% if @item.is_active == false %>
            <span class="text-danger font-weight-bold">販売停止中</span>
          <% else %>
           <span class="text-success font-weight-bold">販売中</span>
          <% end %>
  </td></tr>
  <tr>  <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-outline-success" %>  
   </td></tr>
    </table> </div> </div> </div> </div>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>
     
    <div class='row'>
      <div class='col-md-12 offset-md-1'>
        <h2>注文履歴詳細</h2>
        <!-- 購入者情報 -->
        <table class='table table-hover table-inverse'>
          <tr>
              <th>購入者</th>
              <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
          </tr>
          <tr>
              <th>注文日</th>
              <td><%= @order.created_at %></td>
          </tr>
          <tr>
              <th>配送先</th>
              <td><%= @order.address %></td>
          </tr>
          <tr>
              <th>注文ステータス</th>
              <td>

                <%= form_with model: @order, url: admin_order_path, local:true do |f| %>
                  <%#= f.collection_select :status, @order, :status, :status_i18n %>
                  <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
                  <%= f.submit "更新", :class=>"btn btn-success"%>
                <% end %>
              </td>
          </tr>
          <tr>
              <th>id</th>
              <td><%= @order.id %></td>
          </tr>
        </table>
        
        <!-- 購入商品情報 -->
        
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @order_detail.each do |order_detail| %>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= order_detail.item.price %>円</td>
                <td><%= order_detail.amount %></td>
                <td><%= order_detail.item.price * order_detail.amount%>円</td>
                <td><%= order_detail.making_status_i18n %></td>
                <td>
                  <%= form_with model: order_detail, url:admin_order_detail_path(order_detail.id),  local:true do |f| %>
                    <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                    <%= f.submit "更新", :class=>"btn btn-success"%>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
       </div>
     </div>
</div>