config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords,], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "homes#top"
    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:edit, :show, :update, :index]
    resources :orders, only: [:update, :show]
    resources :order_details, only: [:update]
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "/orders/thanks" => "orders#thanks"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:edit, :update]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete "/cart_items" => "cart_items#all_destroy"
    get 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders, only: [:new, :create, :index, :show]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :addresses, only: [:index, :edit ,:create, :update, :destroy]
  end
 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

  private
def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  attachment :image
  belongs_to :genre 
  
  def with_tax_price
    (price * 1.1).floor
  end
  # 消費税を求めるメソッド
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, payment_confirmation: 1, production: 2, preparing_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { not_startable: 0, waiting_production: 1, production: 2, complete_production: 3 }

  
  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def create
    @genre = Genre.new(genre_params)
    
    if @genre.save
      flash[:notice] = 'You have created genre successfully.'
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end

  end

  def index
    #@genres = Genre.all
    @genres = Genre.page(params[:page]).reverse_order
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = 'You have updated genre successfully.'
       redirect_to admin_genres_path
    else
       render :edit
    end
    
  end

  # 投稿データのストロングパラメータ
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders= Order.page(params[:page]).reverse_order
    
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 
 def new
    @item=Item.new
    
 end
 
  def create
    @item = Item.new(item_params)
    # if
    @item.save
    redirect_to admin_item_path(@item)
    # else
    #   redirect_to request.referer,notice:"新規登録できませんでした"
    # end 
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = 'You have updated item successfully.'
       redirect_to admin_item_path
    else
       render :edit
    end
  end
  
  def index 
    @items=Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  
  private
    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

       <h1><a href="/">ながのCAKE</a>  </h1>
    <!--会員がログインしている場合-->
     <nav class="pc-nav">
     <ul>
    <% if customer_signed_in? %>

     <li class="name-link">ようこそ、<%= current_customer.last_name + current_customer.first_name %>様！</li>

     <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " 商品一覧", items_path ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " カート", cart_items_path,class: 'btn btn-outline-secondary mx-3 my-1' %></li>
     <li><%= link_to " マイページ",customers_my_page_path,class: 'btn btn-outline-secondary mx-3 my-1' %></li>
     <!--管理者がログインしている場合-->
    <% elsif admin_signed_in? %>
     <li><%= link_to " 商品一覧", admin_items_path ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " 会員一覧", admin_customers_path ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " 注文履歴一覧", admin_root_path,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " ジャンル一覧", admin_genres_path ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li><%= link_to " ログアウト", destroy_admin_session_path, method: :delete ,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
    <!--ログインしてない場合-->
    <% else %>
     <li><%= link_to "About", about_path ,class: 'btn btn-outline-secondary mx-3 my-1'%>  </li>
     <li><%= link_to "商品一覧", items_path,class: 'btn btn-outline-secondary mx-3 my-1'%> </li>
     <li> <%= link_to "新規登録", new_customer_registration_path,class: 'btn btn-outline-secondary mx-3 my-1'%></li>
     <li> <%= link_to "ログイン", new_customer_session_path,class: 'btn btn-outline-secondary mx-3 my-1'%>  </li>
    <% end %>

    <!-- ログアウト機能仮ここまで -->
     <%= form_with url: items_path, local: true, method: :get do |f| %>
      <%= f.text_field :word  %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %> </ul>  </nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>